### ISSUE TITLE
Omega index with high score

### ISSUE THREAD

**Issue by Yuri-Nassar** [eXascaleInfolab/xmeasures#1]
Hello.
I'm testing the omega index method (original and soft), however, I'm getting a result that doesn't make sense in my view, and I didn't find a reason in the article for that.
I have a file with the expected (ground-truth, gt.cnl) and another with the result of the clustering algorithm (cs.cnl). gt.cnl has **10** groups with **132079** nodes and cs.cnl with **5** groups and **96000** nodes. Using the omega index the score was equal to **0.90** (e.g., ./xmeasures -ox gt.cnl cs.cnl).
In my view, this result does not make sense with what I expected in the ground-truth. Does it is not considered the number of clusters in the analysis? Can anyone give me some guidance? Is there a more detailed manual of using xmeasures?
Thank you for your help.

**Comment by luav** [comment]
Hello Yuri,
> Does it is not considered the number of clusters in the analysis?

Omega index by definition* does not consider the number of clusters (groups). This measure evaluates co-occurrences of nodes in two collections of clusters.
*&nbsp;L. M. Collins and C. W. Dent, “Omega: A general formulation of the rand index of cluster recovery suitable for non-disjoint solutions,” Multivariate Behavioral Research, vol. 23, no. 2, pp. 231–242, 1988

> Can anyone give me some guidance? Is there a more detailed manual of using xmeasures?

So, before evaluating any accuracy measures, you should [read about them](https://github.com/eXascaleInfolab/xmeasures/blob/master/docs/xmeasures.pdf) and select the one that matches your expectations and demands.

Also, you can try other implementations to validate the evaluation correctness. You can start with ParallelComMetric and  CluSim in the [Related Projects](https://github.com/eXascaleInfolab/xmeasures#related-projects).
